#!/bin/bash -x


#laptop screen
LSCREEN="eDP-1"
TMONITOR="DP-1-2"
RMONITOR="DP-1-3" #VGA


DESKTOPMODE=1
LAPTOPMODE=0
MODE=$LAPTOPMODE

function refreshConky()
{
	pkill conky
	sleep 3
	conky&
}

function activateDesktopMode()
{
	echo "Activating Desktop Mode"

	xrandr --output $TMONITOR --mode 1920x1080 --primary
	sleep 1
	xrandr --output $RMONITOR --mode 1920x1080 --right-of $TMONITOR
	sleep 1
	xrandr --output $LSCREEN --mode 1920x1080_pbidwell --below $TMONITOR

	MODE=$DESKTOPMODE

    #refreshConky

    # shuffle workspaces across monitors appropriately
    i3-msg "workspace 1; move workspace to $LSCREEN; workspace 2; move workspace to $TMONITOR; workspace 3; move workspace to $RMONITOR"
}

function activateLaptopMode()
{
	echo "Activating Laptop Mode"

    # Aggregate workspaces to laptop screen
    i3-msg "workspace 1; move workspace to $LSCREEN; workspace 2; move workspace to $LSCREEN; workspace 3; move workspace to $LSCREEN"

	xrandr --output $LSCREEN --mode 1920x1080_pbidwell --primary
	sleep 1
	xrandr --output $TMONITOR --off 
	sleep 1
	xrandr --output $RMONITOR --off 

	MODE=$LAPTOPMODE

#	refreshConky

}

function readyForDesktopMode()
{
	! xrandr | grep $TMONITOR | grep disconnected && return 0 || return 1
}

function isInDesktopMode()
{
	[ $MODE -eq $DESKTOPMODE ] && return 0 || return 1
}

#####################################
# MAIN
#####################################

# Add the custom resolution
xrandr --newmode "1920x1080_pbidwell"  172.80  1920 2040 2248 2576  1080 1081 1084 1118  -HSync +Vsync
xrandr --addmode eDP-1 "1920x1080_pbidwell"

activateLaptopMode

while true
do
	sleep 5

	! isInDesktopMode && readyForDesktopMode && activateDesktopMode

	isInDesktopMode && ! readyForDesktopMode && activateLaptopMode

done
